#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

export DEBIAN_FRONTEND=noninteractive

trap ctrl_c INT

function ctrl_c(){
	echo -e "\n${yellowColour}[*]${endColour}${grayColour}Saliendo${endColour}"
	tput cnorm; rm -rf resultado.txt 2>/dev/null
	exit 0
}

function helpPanel(){
    echo -e "\n${yellowColour}[*]${endColour}${grayColour} Uso: ./decrypt.sh -a linrar -n (archivo)${endColour}"
    echo -e "\n\t${purpleColour}a)${endColour}${yellowColour} Modo de ataque${endColour}"
    echo -e "\t\t${redColour}linrar${endColour}"
    echo -e "\t\t${redColour}linzip${endColour}"
    echo -e "\t${purpleColour}n)${endColour}${yellowColour} Archivo para desenciptar${endColour}"
    echo -e "\t${purpleColour}h)${endColour}${yellowColour} Mostrar este panel de ayuda${endColour}\n"
    exit 0

	exit 0
}

function dependencies(){
	tput civis
	clear; dependencies=(john hashcat)

	echo -e "${yellowColour}[*]${endColour}${grayColour} Comprobando programas necesarios...${endColour}"
	sleep 2

	for program in "${dependencies[@]}"; do
		echo -ne "\n${yellowColour}[*]${endColour}${blueColour} Herramienta${endColour}${purpleColour} $program${endColour}${blueColour}...${endColour}"

		test -f /usr/bin/$program

		if [ "$(echo $?)" == "0" ]; then
			echo -e " ${greenColour}(V)${endColour}"
		else
			echo -e " ${redColour}(X)${endColour}\n"
			echo -e "${yellowColour}[*]${endColour}${grayColour} Instalando herramienta ${endColour}${blueColour}$program${endColour}${yellowColour}...${endColour}"
			apt-get install $program -y > /dev/null 2>&1
		fi; sleep 1
	done
}

function startAttack(){
		clear
	if [ "$(echo $attack_mode)" == "linrar" ]; then

		resultado=$(rar2john ${networkCard} | grep -o ':.*' | sed 's/://')
		echo "$resultado" > resultado.txt
		hashcat -m 13000 -a3 resultado.txt '?d?d?d?d'

	elif [ "$(echo $attack_mode)" == "linzip" ]; then
		clear
		echo -e "${blueColour}[*]${endColour}${grayColour} Iniciando ataque de diccionario${endColour}"
		sleep 1
		zip2john ${networkCard} > archivo.hash
		john --wordlist=/home/wilcox/Desktop/diccionario.txt archivo.hash
		cat archivo.hash | grep -o ':.*' | sed 's/://' > archivo2.hash
		hashcat -m 17200 -a3 archivo2.hash ?d?d?d?d --show | grep -o ':.*' | sed 's/://'
    fi
}

# Main Function

if [ "$(id -u)" == "0" ]; then
	declare -i parameter_counter=0; while getopts ":a:n:h:" arg; do
		case $arg in
			a) attack_mode=$OPTARG; let parameter_counter+=1 ;;
			n) networkCard=$OPTARG; let parameter_counter+=1 ;;
			h) helpPanel;;
		esac
	done

	if [ $parameter_counter -ne 2 ]; then
		helpPanel
	else
		dependencies
		startAttack
		tput cnorm; rm -rf archivo.hash archivo2.hash 2>/dev/null
	fi
else
	echo -e "\n${redColour}[*] No tienes suficientes privilegios${endColour}\n"
fi
